name: Windows tests

on:
  push:
    branches: '*'
  pull_request:
    branches:
    - master

jobs:
  windows:
    name: Windows Py${{ matrix.PYTHON_VERSION }}
    runs-on: windows-latest
    env:
      CI: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      RUNNER_OS: 'windows'
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ['3.6', '3.7', '3.8']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
           activate-environment: test
           auto-update-conda: false
           auto-activate-base: false
           python-version: ${{ matrix.PYTHON_VERSION }}
      - name: Install package dependencies
        shell: bash -l {0}
        run: |
          conda env update --file requirements/environment.yml
          pip install https://github.com/jupyter/jupyter_client/archive/master.zip --force-reinstall
          pip install --upgrade pywin32
      - name: Show environment information
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run tests
        shell: bash -l {0}
        run: pytest -x -vv --cov=qtconsole qtconsole
